[package]
name = "wm"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-keyboard.workspace = true

# libstd.path = "../libstd"
hyperion-syscall.path = "../../crates/syscall"
hyperion-color.path = "../../crates/color"
hyperion-windowing.path = "../hyperion-windowing"

[lints]
workspace = true
