[package]
name = "coreutils"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", default-features = false }
libstd.path = "../../crates/libstd"
hyperion-num-postfix.path = "../../crates/num-postfix"
