[package]
name = "hyperion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["limine"]
limine = ["dep:limine"]
bootboot = []
multiboot1 = []
multiboot2 = []
# Pick limine OR bootboot OR multiboot1 OR multiboot2, they conflict with eachother

# [lib]
# crate-type = ["staticlib"]

[dependencies]
spin = "0.9.4"
volatile = "0.4.5"
x86_64 = "0.14.10"
uart_16550 = "0.2.18"
limine = { version = "0.1.9", optional = true }
#tracing = { version = "0.1.37", default-features = false }
