[package]
name = "hyperion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["limine"]
limine = ["dep:limine"]
bootboot = []
multiboot1 = []
multiboot2 = []
# Pick limine OR bootboot OR multiboot1 OR multiboot2, they conflict with eachother

[dependencies]
spin = "0.9"
volatile = "0.4"
x86_64 = "0.14"
uart_16550 = "0.2"
pc-keyboard = "0.7"
# bitvec = "1.0.1"
#tracing = { version = "0.1.37", default-features = false }

[dependencies.limine]
# git = "https://github.com/limine-bootloader/limine-rs"
# rev = "c2fbc349419d4330b80e053019ad2fe504a61764"
version = "0.1"
optional = true

#[dependencies.itertools]
#version = "0.10.5"
#default-features = false

[dependencies.chrono]
version = "0.4"
default-features = false

[build-dependencies]
image = "0.24"
chrono = "0.4"
