[package]
name = "hyperion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.9.4"
volatile = "0.4.5"
#tracing = { version = "0.1.37", default-features = false }
