[config]
default_to_workspace = false

[tasks.run]
condition.files_modified = { input = [], output = ["bin"] }
script = "echo 'test' > bin"

[tasks.task]
dependencies = ["run"]
condition.files_modified = { input = ["bin"], output = [] }
script = "cat bin"

