[package]
name = "term"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2"
image = { version = "0.25", default-features = false, features = ["bmp"] }
# libstd.path = "../libstd"
hyperion-color.path = "../../crates/color"
hyperion-escape.path = "../../crates/escape"
hyperion-syscall.path = "../../crates/syscall"
hyperion-windowing.path = "../hyperion-windowing"

[lints]
workspace = true
