[package]
name = "hyperion-atomic-map"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = "0.6"
