[package]
name = "libstd"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin.workspace = true

hyperion-slab-alloc.path = "../slab-alloc"
hyperion-syscall.path = "../syscall"
