[package]
name = "sample-elf"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86_64.workspace = true    

libstd.path = "../../crates/libstd"
