[package]
name = "hyperion-slab-alloc"
version.workspace = true
edition.workspace = true

[features]
log = ["hyperion-log"]
rustc-dep-of-std = [
  "core",
	"compiler_builtins",
]

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperion-log = { path = "../log", optional = true }
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1", optional = true }
