[package]
name = "hyperion-slab-alloc"
version.workspace = true
edition.workspace = true

[features]
log = ["hyperion-log"]

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck.workspace = true
lock_api.workspace = true
spin.workspace = true

hyperion-log = { path = "../log", optional = true }
