[package]
name = "hyperion-sync"
description = "thread safe data structures used in the hyperion kernel"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
