[package]
name = "hyperion_kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11.0"
#bitflags = "1.3.2"
x86_64 = "0.14.10"
spin = "0.9.4"
