[package]
name = "hyperion-abi"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rustc-dep-of-std = [
  "core",
	"compiler_builtins",
  "hyperion-syscall/rustc-dep-of-std",
  "hyperion-slab-alloc/rustc-dep-of-std",
]

[dependencies]
hyperion-syscall.path = "../../crates/syscall"
hyperion-slab-alloc.path = "../../crates/slab-alloc"
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1", optional = true }

[lints]
workspace = true
