[package]
name = "fbtest"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86_64.workspace = true    
libm = "0.2"

libstd.path = "../../crates/libstd"
hyperion-color.path = "../../crates/color"
