[package]
name = "fbtest"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2"
glam = { version = "0.24", default-features = false, features = ["libm"] }

libstd.path = "../../crates/libstd"
hyperion-color.path = "../../crates/color"
