[build]
# this is so that rust-analyzer wouldn't fight me constantly
# target = "x86_64-unknown-none"
rustflags = [
    "-C", "force-frame-pointers=true",
    #"-C", "linker=clang-16",
    #"-C", "link-arg=-fuse-ld=lld"
]

[unstable]
bindeps = true
