[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64
  -cpu rv64
  -machine virt
  -serial mon:stdio
  -m 80M
  -s
  -vga virtio
  -append 'hello'
  -kernel"""
# -nographic

[unstable]
bindeps = true
