[package]
name = "hyperion-interrupts"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam.workspace = true

hyperion-macros.path = "../macros"
