[package]
name = "term"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# libstd.path = "../libstd"
hyperion-syscall.path = "../../crates/syscall"
hyperion-color.path = "../../crates/color"

[lints]
workspace = true
