[package]
name = "hyperion-vfs"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu.workspace = true
lock_api.workspace = true
async-trait = "0.1"

hyperion-futures.path = "../futures"
hyperion-log.path = "../log"
hyperion-mem.path = "../mem"
