[package]
name = "hyperion-vfs"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin.workspace = true
snafu.workspace = true

hyperion-log.path = "../log"
