[package]
name = "hyperion-vfs"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu.workspace = true
spin.workspace = true
crossbeam.workspace = true
lock_api.workspace = true

hyperion-log.path = "../log"
hyperion-syscall.path = "../syscall"
