[package]
name = "hyperion-vfs"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"

hyperion-syscall.path = "../syscall" # Error enum
hyperion-futures.path = "../futures" # async Mutex
hyperion-log.path = "../log" # logging
# hyperion-mem.path = "../mem" # memory mapping
