[package]
name = "hyperion-syscall"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rustc-dep-of-std = [
  "core",
	"compiler_builtins",
  "bitflags/rustc-dep-of-std",
]

[dependencies]
bitflags.workspace = true
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1", optional = true }
# strum = { version = "0.25", default-features = false, features = ["derive"] }
