[package]
name = "hyperion-syscall"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
# strum = { version = "0.25", default-features = false, features = ["derive"] }
