[package]
name = "mem"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
spin.workspace = true

log.workspace = true
riscv64-vmm.workspace = true
util.workspace = true
