[package]
name = "hysh"
version.workspace = true
edition.workspace = true

[dependencies]
hyperion-syscall.path = "../../crates/syscall"
hyperion-escape.path = "../../crates/escape"

[lints]
workspace = true
