[package]
name = "riscv64-vmm"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bitflags.workspace = true

log.workspace = true
mem.workspace = true
riscv64-util.workspace = true
util.workspace = true
