name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
      
    #- run: apt update # only on `act`

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: jq xorriso qemu-system-x86 ripgrep
        version: 1.0

    - name: Install latest rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-none, x86_64-unknown-linux-gnu
        components: rustfmt, clippy

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    #- name: Cache Build
    #  uses: Swatinem/rust-cache@v2.5.0

    - name: Run tests
      run: make nextest

    - name: Run QEMU tests
      run: make KVM=false test

    - name: Run Clippy
      run: cargo clippy --workspace --exclude=term --exclude=wm --exclude=hyperion-windowing -- -Dwarnings

    - name: Run Rustfmt
      run: cargo fmt --all -- --check

    - name: Run Rustdoc
      run: cargo doc --no-deps && ls ./target/doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./target/doc
