name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
      
    #- run: apt update # only on ACT

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: jq xorriso qemu-system-x86 ripgrep
        version: 1.0

    - name: Install latest rust nightly
      if: steps.cache-rustup-restore.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-none
        components: rustfmt, clippy

    #- name: Cache Build
    #  uses: Swatinem/rust-cache@v2.5.0

    - name: Build
      run: make build

    - name: Run tests
      run: make unittest

    - name: Run QEMU tests
      run: make KVM=false test

    - name: Run Clippy
      run: cargo clippy --all -- -D warnings

    - name: Run Rustfmt
      run: cargo fmt --all -- --check
